s6-rc-db-update-hook: support custom user sv path
Finally got around to working on this. Some users in #artix and #s6
correctly pointed out that Artix's s6 implementation is heavily
dependent on s6-rc-bundle and is not very friendly about letting users
edit and make their own services. Specifically, the default bundle and
its contents are commonly overwritten on every s6-scripts update. This
adds some groundwork to splitting the s6-rc database compilation into
multiple directories. ${USERSVPATH} is the path for custom user service
files. The default bundle will live here along with anything else not
installed by the user. ${BACKUPSVPATH} is strictly for emergency usage
when the compilation fails. These are not to be altered by users.

diff --git a/s6/scripts/s6-rc-db-update-hook b/s6/scripts/s6-rc-db-update-hook
--- a/s6/scripts/s6-rc-db-update-hook
+++ b/s6/scripts/s6-rc-db-update-hook
@@ -42,6 +42,8 @@ in_newbundle() {
 RCPATH='/etc/s6/rc'
 DBPATH="${RCPATH}/compiled"
 SVPATH='/etc/s6/sv'
+USERSVPATH='/etc/s6/usersv'
+BACKUPSVPATH='/etc/s6/backupsv'
 SVDIRS='/run/s6-rc/servicedirs'
 TIMESTAMP=$(date +%s)
 
@@ -58,9 +60,13 @@ if [ -e "${DBPATH}" ]; then
     )
 fi
 
-if ! s6-rc-compile "${DBPATH}"-"${TIMESTAMP}" "${SVPATH}"; then
-    echo "Error compiling database."
-    echo "Please double check the ${SVPATH} directories. Exiting."
+if ! s6-rc-compile "${DBPATH}"-"${TIMESTAMP}" "${SVPATH}" "${USERSVPATH}"; then
+    echo "Error compiling database. Falling back to the system default!"
+    echo "Please double check the ${USERSVPATH} directories."
+    if ! s6-rc-compile "${DBPATH}"-"${TIMESTAMP}" "${SVPATH}" "${BACKUPSVPATH}"; then
+        echo "The system default compilation failed. Something is really wrong with your service directories!"
+        echo "Check your ${SVPATH} and ${BACKUPSVPATH} directories."
+    fi
     exit 1
 fi
 
